name: Retrain Model

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # daily at 00:00 UTC

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2️⃣ Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r phishing_detector/requirements.txt

      # 4️⃣ Clean __pycache__ and .pyc files
      - name: Clean cache
        run: |
          find . -name "*.pyc" -delete
          find . -name "__pycache__" -type d -exec rm -rf {} +

      # 5️⃣ Run retraining script
            # 5️⃣ Run retraining script only if feedback data exists
      - name: Run retraining
        id: retrain
        run: |
          if [ -f feedback_data.csv ]; then
            python phishing_detector/src/retrain_model.py
          else
            echo "⚠️ No feedback data found. Skipping retraining."
          fi
         
      # 6️⃣ Commit and push updated model
      - name: Commit retrained model
        if: success()  # only run if previous step succeeds
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add models/final/naive_bayes_model.joblib models/final/tfidf_vectorizer_advanced.joblib
          git commit -m "🤖 Auto-update: retrained model"
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/AlphaG24/Ai-phishing-email-detector.git main || echo "⚠️ Nothing to commit"
