name: Retrain Model

# Triggers: manual + daily schedule
on:
  workflow_dispatch:   # Allows manual trigger
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r phishing_detector/requirements.txt

      # 4️⃣ Run retraining script
      - name: Run retraining
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # GitHub secret
        run: |
          python phishing_detector/src/retrain_model.py
